# Generated by Django 5.1.4 on 2024-12-22 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('gol_scored', models.PositiveIntegerField(default=0)),
                ('gol_conceded', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('last_game_date', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.CharField(blank=True, default='/static/images/user/default.jpg', max_length=255, null=True)),
                ('friends', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
