# Generated by Django 5.1.4 on 2024-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_game_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rank',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
    ]
