# Generated by Django 5.1.4 on 2024-12-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_last_game_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intra_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
